name: lint

on: [pull_request]

jobs:
  build:
    name: 'Lint docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: 'Install Python packages'
        run: pip install -r requirements.txt
      - name: 'Build docs'
        run: mkdocs build --config-file config/en/mkdocs.yml --strict
